# Generated by Django 4.0.3 on 2022-05-27 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_film', models.CharField(max_length=200, verbose_name='Название фильма')),
                ('dic_film', models.TextField(verbose_name='Описание фильма')),
                ('session_num', models.IntegerField(verbose_name='Количество сессий')),
            ],
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_session', models.IntegerField(verbose_name='Номер сессии')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
            ],
        ),
        migrations.CreateModel(
            name='SessionsOfFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.film')),
                ('num_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='films.session')),
            ],
        ),
    ]
